baseURL = "http://example.org/"
copyright = "© Copyright notice"
disqusShortname = "localhost"
googleAnalytics = "UA-123-45"
languageCode = "en-us"
paginate = 10
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
pygmentsstyle = "solarized-dark"
summaryLength = 20
theme = "ezhil"
title = "Web de prueba"
[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4
[[menu.main]]
name = "About"
url = "/about"
weight = 3
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[params]
customCSS = "css/custom.css"
customDarkCSS = "css/custom-dark.css"
customJS = ["js/abc.js", "js/xyz.js", "https://code.jquery.com/jquery-3.4.1.js"]
disableDisqusTypes = ["page"]
favicon = "icons/myicon.png"
featherIconsCDN = true
mainSections = ["posts"]
mode = "dark"
subtitle = "Clean and minimal personal [blog theme for Hugo](https://github.com/vividvilla/ezhil)"
[[params.social]]
icon = "github"
name = "Github"
url = "https://github.com/vividvilla/ezhil"
[[params.social]]
icon = "twitter"
name = "Twitter"
url = "https://twitter.com/gohugoio"
[taxonomies]
tag = "tags"
